[settings]
auto_update = true
auto_update_check_duration = "3d"

[settings.status]
show_env = true
show_tools = true

[tools]
age = "latest"
eza = "latest"
starship = "latest"
usage = "latest"
zoxide = "latest"
jj = "latest"
"github:iffse/pay-respects" = "latest"
"github:tbillington/kondo" = "latest"
"forgejo:mergiraf/mergiraf" = "latest"

[bootstrap.user]
login_shell = "/bin/zsh"

[bootstrap.mise_shell_activate]
zprofile = "shims"
zshrc = "activate"
bash_profile = "shims"
bashrc = "activate"
