[settings.cargo]
binstall = true

[bootstrap.packages]
"brew:gettext" = "latest"
"brew:git" = "latest"
"brew-cask:discord" = "latest"
"brew-cask:nvidia-geforce-now" = "latest"
"brew-cask:signal" = "latest"
"brew-cask:vlc" = "latest"

[tools]
"cargo:garage" = "latest"
dive = "latest"
github-cli = "latest"
shellcheck = "latest"

rust = "latest"
cargo-binstall = "latest"
"cargo:bacon" = "latest"
"github:crisidev/bacon-ls" = "latest"
